version: "3.4"

services:
  catalogdb:
    container_name: catalogdb
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dev123
      POSTGRES_DB: CatalogDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    restart: always
    
  distributedcache:
    image: redis
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  basketdb:
    container_name: basketdb
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dev123
      POSTGRES_DB: BasketDb
    ports:
      - "5434:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data
    restart: always

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    restart: always

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:


