version: "3.4"

services:
  catalogdb:
    container_name: catalogdb
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dev123
      POSTGRES_DB: CatalogDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    restart: always
    
  distributedcache:
    image: redis
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  basketdb:
    container_name: basketdb
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dev123
      POSTGRES_DB: BasketDb
    ports:
      - "5434:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data
    restart: always

  messagebroker:
    container_name: messagebroker
    image: rabbitmq:management
    hostname: ecommerce-mq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    healthcheck:
      # Explicit internal check using rabbitmq diagnostic commands to ensure port 5672 is open
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    restart: always

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:



