version: "3.4"

services:
  catalogdb:
    container_name: catalogdb
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dev123
      POSTGRES_DB: CatalogDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
    restart: always
    
  basketdb:
    container_name: basketdb
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dev123
      POSTGRES_DB: BasketDb
    ports:
      - "5434:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data
    restart: always

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    restart: always

volumes:
  postgres_catalog:
  postgres_basket:
